### ISSUE TITLE
customise "card" width?

### ISSUE THREAD

**Issue by yeahman45** [Archmonger/Improved-Plex-Mobile#7]
First of all thx for this great css to make mobile version of plex usable!
is there a way to increase the width of the cards more?
https://i.imgur.com/ytvTxXY.png

I see this js file :
https://github.com/Archmonger/Improved-Plex-Mobile/blob/master/archived/plex_mobile.js

I have tried adding it but I get a black screen. Does not seem to have any error in console.

**Comment by Archmonger** [comment]
That JS file exists within our archived folder, which means it has been retired. Functionality previously contained within that javascript file has been worked around, and you'd definitely would see unexpected behavior upon use.

I've attempted increasing card width in the past but unfortunately due to the way Plex generates them... it appears to be impossible to change the size of these cards without fundamentally breaking the page or ruining page aesthetics.

If you have any additional questions, feel free to message us on Discord! [https://discord.gg/sfjkDaM](https://discord.gg/sfjkDaM)
