### ISSUE TITLE
Nginx setting to add css file as local file

### ISSUE THREAD

**Issue by g-vdn** [Archmonger/Improved-Plex-Mobile#8]
What would be the setting to add the css file as a local file, so nginx wouldn't have to go online to pick-up the css file?

Tried adding

location / {
....
root /opt/Improved-Plex-Mobile;
include /etc/nginx/mime/types;

proxy_pass http://127.0.0.1:3000;
.......

sub_filter ...... "href=plex_mobile.css" ....
...
}

But it's not loading the css file.

Thanks

**Comment by Archmonger** [comment]
Nginx has a tutorial on [serving static files.](https://docs.nginx.com/nginx/admin-guide/web-server/serving-static-content/)
I've never set up this use case, but based on what I was able to gather:

```nginx

root /opt/Improved-Plex-Mobile;

include /etc/nginx/mime/types;

location /
{
    # Attempt to serve a file from the root directory before routing to the reverse proxy
    try_files $uri $uri/ @backend; 
}

location @backend
{
    proxy_pass http://127.0.0.1:3000;
}
```
Let me know if this works.

**Comment by g-vdn** [comment]
With $uri/ I get a 403 error. If I remove that, css is somehow loading but page is not displayed properly

**Comment by Archmonger** [comment]
Could be forbidden due to file permission issues. Perhaps the CSS file you're creating is not owned by the user that Nginx is running as.

**Comment by g-vdn** [comment]
Permissions are ok, user www-data has access to full path. I also moved the folder into /var/www, same thing. 

L.E. Placing the statement autoindex on; in the / location gets rid of the 403 error, with $uri/ included. But css still seems off. Ill upload a screenshoot.

**Comment by g-vdn** [comment]
![Screenshot_20210212_114810.jpg](https://user-images.githubusercontent.com/58138236/107759184-3a599180-6d28-11eb-97c2-640cdb79d3b6.jpg)

**Comment by Archmonger** [comment]
Since I don't have experience with serving static files in tandem with a reverse proxy, I highly recommend asking for support in the #groups channel of the [Organizr discord](https://organizr.app/discord). They have a whole lot of Nginx professionals that are willing to help people with self-hosting issues, especially related to my CSS. The solution is likely going to look similar to the one I posted, but I'm sure I'm missing something.

Otherwise, reading the Nginx documentation may be the best way around this.

Apologies that I'm unable to directly help but this Nginx config is outside my expertise.

Let me know if you find a solution and I'll post it on the wiki for others in the future!
